[server]
bind-address = "0.0.0.0"
bind-port = 12864
host-name = "shuttlepub.localhost"

[server.keypair]
private = "./.keys/private.pem"
public = "./.keys/public.pem"

[server.overrides."misskey.localhost"]
resolve = "127.0.0.1:4430"
certificate = "./.certs/misskey.crt"

[server.overrides."mastodon.localhost"]
