[package]
name = "app-cmd"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
kernel.workspace = true
thiserror.workspace = true
error-stack.workspace = true